//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCKU_Eat
{
    using System;
    using System.Collections.Generic;
    
    public partial class 餐廳
    {
        public int Id { get; set; }
        public string 店名 { get; set; }
        public string 地址 { get; set; }
        public Nullable<double> 經度 { get; set; }
        public Nullable<double> 緯度 { get; set; }
        public Nullable<double> 距離 { get; set; }
        public string 餐廳類別 { get; set; }
    }
}
